name: Push to Azure Container Registry
on:
  push:
    branches:
      - main
      - devops/gha-workflow-update-2

jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
    
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_NAME }}
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: Create .env file
        run: |
          touch WebsiteArchiver/.env
          echo AZURE_BLOB_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }} >> WebsiteArchiver/.env
          echo AZURE_BLOB_STORAGE_CONTAINER_NAME=${{ secrets.AZURE_BLOB_STORAGE_CONTAINER_NAME }} >> WebsiteArchiver/.env
          echo DOMAIN=${{ secrets.DOMAIN }} >> WebsiteArchiver/.env

      - name: Build Docker image
        run: |
          cd WebsiteArchiver
          docker-compose build

      - name: Push Docker image to Azure Container Registry
        run: |
          docker tag websitearchiver:latest ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/test:${{ github.sha }}
          docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/test:${{ github.sha }}
