name: Push to Azure Container Registry
on:
  push:
    branches:
      - main

jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
    
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: Create .env file
        run: |
          touch .env
          echo AZURE_BLOB_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }} >> .env
          echo AZURE_BLOB_STORAGE_CONTAINER_NAME=${{ secrets.AZURE_BLOB_STORAGE_CONTAINER_NAME }} >> .env
          echo DOMAIN=${{ secrets.DOMAIN }} >> .env

      - name: Build Docker image
        run: docker-compose build 

      - name: Push Docker image to Azure Container Registry
        run: docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/website-archiver:${ github.sha }
